version: "3"
services:
  client_dev:
    build: ./client
    command: sh -c "npm install && npm run dev"
    ports:
      - 8000:3000
    working_dir: /home/app/client
    volumes:
      - ./client:/home/app/client
  api_dev:
    build: ./api
    command: sh -c "npm run migrate-db && npm install && npm run dev"
    ports:
      - 8001:3001
    working_dir: /home/app/api
    volumes:
      - ./api:/home/app/api
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: recipe_db_user
      POSTGRES_DB: recipe_db
      POSTGRES_PASSWORD: root#root
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

